services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: membersdb
    ports:
      - "3306:3306"
    volumes:
      - /home/ec2-user/mysql-data:/var/lib/mysql
    networks:
      - appnet

  app:
    image: mpl143/two-tier-flask-app:latest
    container_name: flask-app
    restart: always
    depends_on:
      - db
    environment:
      MYSQL_HOST: 52.16.125.217
      MYSQL_USER: root
      MYSQL_PASSWORD: root123
      MYSQL_DATABASE: membersdb
    ports:
      - "5000:5000"
    networks:
      - appnet

networks:
  appnet:
    driver: bridge

volumes:
  mysql_data:
